{{- if .Values.jobs.cacheConfig.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "fastretro.fullname" . }}-cache-config
  labels:
    {{- include "fastretro.labels" . | nindent 4 }}
    app.kubernetes.io/component: cache
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: {{ .Values.jobs.cacheConfig.backoffLimit }}
  template:
    metadata:
      labels:
        {{- include "fastretro.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: cache
    spec:
      restartPolicy: {{ .Values.jobs.cacheConfig.restartPolicy }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fastretro.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: cache-config
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - sh
            - -c
            - |
              php artisan config:cache
              php artisan route:cache
              php artisan view:cache
          envFrom:
            - configMapRef:
                name: {{ include "fastretro.fullname" . }}
            - secretRef:
                name: {{ include "fastretro.fullname" . }}
          resources:
            {{- toYaml .Values.jobs.cacheConfig.resources | nindent 12 }}
          volumeMounts:
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}
