apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fastretro.fullname" . }}
  labels:
    {{- include "fastretro.labels" . | nindent 4 }}
type: Opaque
stringData:
  APP_KEY: {{ required "app.key is required" .Values.app.key | quote }}
  REVERB_APP_SECRET: {{ required "reverb.appSecret is required" .Values.reverb.appSecret | quote }}
