apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fastretro.serviceAccountName" . }}
  labels:
    {{- include "fastretro.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
