apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastretro.fullname" . }}
  labels:
    {{- include "fastretro.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fastretro.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastretro.fullname" . }}-reverb
  labels:
    {{- include "fastretro.labels" . | nindent 4 }}
    app.kubernetes.io/component: reverb
spec:
  type: {{ .Values.reverbService.type }}
  ports:
    - port: {{ .Values.reverbService.port }}
      targetPort: reverb
      protocol: TCP
      name: reverb
  selector:
    {{- include "fastretro.selectorLabels" . | nindent 4 }}
